# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MouseJiggler < Formula
  desc "Moves the mouse pointer periodically without clicking"
  homepage "https://github.com/dnjdsxor21/mouse-jiggler-go"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dnjdsxor21/mouse-jiggler-go/releases/download/v0.1.1/mouse-jiggler_0.1.1_darwin_arm64.tar.gz"
    sha256 "babf0153038107caad211f1a20f8bf231cd6f202a41a22058ad3127fff283608"

    define_method(:install) do
      bin.install "mouse-jiggler"
    end
  end

  def caveats
    <<~EOS
      mouse-jiggler needs Accessibility access before it can move the pointer.
      Open System Settings > Privacy & Security > Accessibility, add the
      installed executable, enable it, and run mouse-jiggler again.
    EOS
  end

  test do
    system "#{bin}/mouse-jiggler", "--version"
  end
end
