# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MouseJiggler < Formula
  desc "Moves the mouse pointer periodically without clicking"
  homepage "https://github.com/dnjdsxor21/mouse-jiggler-go"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dnjdsxor21/mouse-jiggler-go/releases/download/v0.3.0/mouse-jiggler_0.3.0_darwin_arm64.tar.gz"
    sha256 "5317503c8b84a8824eb9831f09f3a0397dd7552e7fd53fba9c7d0af6693ba7fd"

    define_method(:install) do
      bin.install "mouse-jiggler"
    end
  end

  def caveats
    <<~EOS
      mouse-jiggler needs Accessibility access before it can move the pointer.
      Open System Settings > Privacy & Security > Accessibility, add the
      installed executable, enable it, and run mouse-jiggler again.
    EOS
  end

  test do
    system "#{bin}/mouse-jiggler", "--version"
  end
end
