# This file was generated by GoReleaser. DO NOT EDIT.
cask "mouse-jiggler" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "6dfe86780dfaa69adf526cdc69970e5408aa2e88230ee969a66249b9f3057354"
      url "https://github.com/dnjdsxor21/mouse-jiggler-go/releases/download/v#{version}/mouse-jiggler_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "mouse-jiggler"
  desc "Moves the mouse pointer periodically without clicking"
  homepage "https://github.com/dnjdsxor21/mouse-jiggler-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mouse-jiggler"

  # No zap stanza required

  caveats <<~EOS
    mouse-jiggler needs Accessibility access before it can move the pointer.
    Open System Settings > Privacy & Security > Accessibility, add the
    installed executable, enable it, and run mouse-jiggler again.
  EOS
end
